name: scrumboard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  appflowy_board: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.0
  kanban_board: ^0.1.0
  localstore: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - 'assets/127.0.0.1+2-client-key.pem'
    - 'assets/127.0.0.1+2-client.p12'
    - 'assets/127.0.0.1+2-client.pem'
